# vim: set ft=zsh
#
#! /bin/zsh


nvim() {
  $HOME/builds/nvim-linux64/bin/nvim $*
}


#Prompt Setup ###
DIR="/home/nxtcoder17/builds/Dots/zsh"
source "$DIR/scripts/alias.sh"
source "$DIR/scripts/env.sh"
source "$DIR/scripts/functions.sh"
source "$DIR/scripts/prompt.sh"
source "$DIR/scripts/lf-icons.sh"

SECRETS_FILE="$HOME/.secrets"
source $SECRETS_FILE


bindkey -v

# History in cache directory:
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.cache/zsh/history
setopt append_history
setopt inc_append_history

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# Edit line in vim with ctrl-e:
autoload edit-command-line;
zle -N edit-command-line
bindkey '^e' edit-command-line

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select {
  zle reset-prompt
  zle -R

  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}

# ci{, ci(, di{ etc..  autoload -U select-bracketed
zle -N select-bracketed
for m in visual viopp; do
  for c in {a,i}${(s..)^:-'()[]{}<>bB'};
  do
    bindkey -M $m $c select-bracketed
  done
done

# zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}

zle -N zle-line-init
echo -ne '\e[5 q'                # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

export KEYTIMEOUT=1

## FZF
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# export npm_config_registry=http://services:4873
NPM_PACKAGES="${HOME}/.local-node"
export PATH="$PATH:$NPM_PACKAGES/bin:$HOME/bin"

[ -f './.sh.env' ] && source './.sh.env'
[ -f './.sh.override' ] && source './.sh.override'
