# /* vim: set ft=sh:*/

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias conn='netctl start wlp19s0-ACET_BH23'
alias mo='mount -t ext4 /dev/sda4 /My_Everything/'
alias xc='xclip -selection clipboard -o '
alias um='umount /dev/sda4'
alias vp='source ~/.local/Virtual_Python/bin/activate'
alias yt='youtube-dl --write-auto-sub '
alias tmuxw='tmux -2u new -s Workspace'
alias mp='mpv --no-audio-display'
alias pinga='ping archlinux.org'

alias scrapper='python ~/Workspace/Projects/Scraper/main.py'
alias pcl='python ~/Workspace/Projects/PCloud/pcloud.py'

alias execute="~/Workspace/Library_Management/execute.sh"

alias pd="python ~/Workspace/Projects/Reborn_Downloader/threaded.py"
alias lynda="bash ~/Tutorials/Lynda_Premiums/lynda_downloader.sh"
